name: ci_pipeline

on:
  push:
    paths:
      - 'API/app.py'
      - 'API/cnn.py'
env:
  IMAGE_NAME: final_api
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and run Docker image
      run:
        docker  build  --tag ${{ env.IMAGE_NAME }} .
    - name: Run docker
        #if: ${{ github.ref == 'refs/heads/main' }} # replace with your branch name
      run:
        docker run -d --name mati -p 8000:8000 ${{ env.IMAGE_NAME }}
    - name: check ip of docker
      run:
        docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mati
    - name: check docker ps
      run:
        docker ps
    - name: check curl of given ip
      run:
        curl http://172.17.0.3:8000/check



    - name: Run tests
      run: docker run --network="host"  ${{ env.IMAGE_NAME }}:latest pytest

    - name: Stop Docker container
      run: docker stop ${{ env.IMAGE_NAME }}
      if: always()

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
