name: ci_pipeline

on:
  push:
    paths:
      - 'API/app.py'
      - 'API/cnn.py'
env:
  IMAGE_NAME: mlopsengineer
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest

    - name: Run Docker image
      run: docker run -d --name api -p 8000:8000 ${{ env.IMAGE_NAME }}:latest

    - name: Run tests
      run: docker run --rm --network="host" -e APP_ENV=test ${{ env.IMAGE_NAME }} pytest

    - name: Stop Docker container
      run: docker stop api
      if: always()

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest
